spring.application.name=School-management-system
server.port=8080

# --- Database Configuration ---
# Changed placeholders to avoid conflicting with Windows system variables like ${username}
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-184425de-abuobernard-2afb.l.aivencloud.com:16535/school_manager_v2?useSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_G-3yS74f9vjRNrvgkdi}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- JPA CONFIG ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT CONFIG ---
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expirationMs=86400000

# --- STATIC RESOURCES ---
spring.web.resources.static-locations=classpath:/static/
spring.mvc.welcome-page=classpath:/static/index.html

# --- EMAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abuobernard@gmail.com
spring.mail.password=phjnxyupxksawrmi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# --- ARKESEL SMS SETTINGS ---
arkesel.api.key=ZXlmeWdLa3ZJWkN1RHlWbmdFVnk
arkesel.sender.id=EXCELSIOR
arkesel.api.url=https://sms.arkesel.com/sms/api

# --- FILE UPLOAD LIMITS ---
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-http-post-size=50MB

# --- LOGGING ---
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod=DEBUG