package com.school.services;

import org.springframework.stereotype.Service;

import javax.sql.DataSource;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

@Service
public class BackupService {

    private final DataSource dataSource;

    public BackupService(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public Path createDatabaseBackup() throws IOException {
        Path backupDir = Paths.get("backups");
        Files.createDirectories(backupDir);

        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String backupFileName = "school_backup_" + timestamp + ".sql";
        Path backupPath = backupDir.resolve(backupFileName);

        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metaData = connection.getMetaData();
            String catalog = connection.getCatalog();
            List<String> tableNames = listTables(metaData, catalog);

            StringBuilder script = new StringBuilder();
            script.append("-- Generated by School Management System\n");
            script.append("SET NAMES utf8mb4;\n");
            script.append("SET FOREIGN_KEY_CHECKS = 0;\n");

            if (catalog != null && !catalog.isBlank()) {
                script.append("CREATE DATABASE IF NOT EXISTS `")
                        .append(escapeIdentifier(catalog))
                        .append("`;\n");
                script.append("USE `")
                        .append(escapeIdentifier(catalog))
                        .append("`;\n");
            }

            for (String tableName : tableNames) {
                script.append("\n-- Table structure for `")
                        .append(escapeIdentifier(tableName))
                        .append("`\n");
                String createStatement = readCreateTableStatement(connection, tableName);
                if (createStatement != null && !createStatement.isBlank()) {
                    script.append("DROP TABLE IF EXISTS `")
                            .append(escapeIdentifier(tableName))
                            .append("`;\n");
                    script.append(createStatement)
                            .append(";\n");
                }

                script.append("\n-- Data for `")
                        .append(escapeIdentifier(tableName))
                        .append("`\n");
                appendInsertStatements(connection, tableName, script);
            }

            Files.writeString(backupPath, script.toString(), StandardCharsets.UTF_8);
            return backupPath;
        } catch (SQLException e) {
            throw new IOException("Database backup failed: " + e.getMessage(), e);
        }
    }

    private List<String> listTables(DatabaseMetaData metaData, String catalog) throws SQLException {
        List<String> tableNames = new ArrayList<>();
        try (ResultSet tables = metaData.getTables(catalog, null, "%", new String[]{"TABLE"})) {
            while (tables.next()) {
                String tableName = tables.getString("TABLE_NAME");
                if (tableName != null && !tableName.startsWith("hibernate")) {
                    tableNames.add(tableName);
                }
            }
        }
        return tableNames;
    }

    private String readCreateTableStatement(Connection connection, String tableName) throws SQLException {
        String escapedTable = escapeIdentifier(tableName);
        try (PreparedStatement statement = connection.prepareStatement("SHOW CREATE TABLE " + escapedTable);
             ResultSet resultSet = statement.executeQuery()) {
            if (resultSet.next()) {
                return resultSet.getString(2);
            }
        }
        return null;
    }

    private void appendInsertStatements(Connection connection, String tableName, StringBuilder script) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM " + escapeIdentifier(tableName));
             ResultSet resultSet = statement.executeQuery()) {
            ResultSetMetaData metaData = resultSet.getMetaData();
            int columnCount = metaData.getColumnCount();
            List<String> columnNames = new ArrayList<>();
            for (int i = 1; i <= columnCount; i++) {
                columnNames.add(metaData.getColumnName(i));
            }

            while (resultSet.next()) {
                script.append("INSERT INTO `")
                        .append(escapeIdentifier(tableName))
                        .append("` (");
                for (int i = 0; i < columnNames.size(); i++) {
                    if (i > 0) {
                        script.append(", ");
                    }
                    script.append("`")
                            .append(escapeIdentifier(columnNames.get(i)))
                            .append("`");
                }
                script.append(") VALUES (");

                for (int i = 1; i <= columnCount; i++) {
                    if (i > 1) {
                        script.append(", ");
                    }
                    Object value = resultSet.getObject(i);
                    script.append(formatValue(value));
                }
                script.append(");\n");
            }
        }
    }

    private String formatValue(Object value) {
        if (value == null) {
            return "NULL";
        }
        if (value instanceof Number || value instanceof Boolean) {
            return value.toString();
        }
        return "'" + value.toString().replace("'", "''") + "'";
    }

    private String escapeIdentifier(String identifier) {
        return "`" + identifier.replace("`", "``") + "`";
    }
}
